[Clock_Location]
latitude = '30.3402S'
longitude = '152.7124E'
altitude = 741

[Clock_Pins]
clock_pins = [24, 25]
led_pin = 22
common_pin = 23

[Clock_Mode]
mode = 'dev'

[Clock_LCD]
lcd_rows = 2
lcd_columns = 16
debounce_sleep = 0.001

[Clock_Logging]
# Relative to main package
folder = "logs"

[Clock_Time]
