from datetime import datetime
from enum import Enum
from .utils import Position

class TimezoneFinder:
    def timezone_at(self, *, lng: float, lat: float) -> str: ...

def timezone_finder(
    latitude: float, longitude: float
) -> _UTCclass | StaticTzInfo | DstTzInfo: ...
def find_sunrise_sunset_times(position: Position) -> dict[TimeOfDay, float]: ...

class TzInfo:
    def localize(self, dt: datetime) -> datetime: ...
    def replace(self, hour, minute, second, microsecond) -> datetime: ...

class _UTCclass(TzInfo): ...
class StaticTzInfo(TzInfo): ...
class DstTzInfo(TzInfo): ...

class TimeOfDay(Enum):
    FIRSTLIGHT: int
    SUNRISE: int
    SUNSET: int
    LASTLIGHT: int
